[package]
name = "javadoc2adoc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tree-sitter = "0.25.2"
tree-sitter-java = "0.23.5"
